md "..\Demo Version"


md "..\Demo Version\LWO"
copy "LWO\BuyFullVersion.lwo" "..\Demo Version\LWO\BuyFullVersion.lwo"
copy "LWO\DebrisGeneral0.lwo" "..\Demo Version\LWO\DebrisGeneral0.lwo"
copy "LWO\DebrisGeneral1.lwo" "..\Demo Version\LWO\DebrisGeneral1.lwo"
copy "LWO\DebrisGeneral2.lwo" "..\Demo Version\LWO\DebrisGeneral2.lwo"
copy "LWO\DebrisGeneral3.lwo" "..\Demo Version\LWO\DebrisGeneral3.lwo"
copy "LWO\DebrisGeneral4.lwo" "..\Demo Version\LWO\DebrisGeneral4.lwo"
copy "LWO\DebrisRockDirt0.lwo" "..\Demo Version\LWO\DebrisRockDirt0.lwo"
copy "LWO\DebrisRockDirt1.lwo" "..\Demo Version\LWO\DebrisRockDirt1.lwo"
copy "LWO\DebrisRockGrass0.lwo" "..\Demo Version\LWO\DebrisRockGrass0.lwo"
copy "LWO\DebrisRockGrass1.lwo" "..\Demo Version\LWO\DebrisRockGrass1.lwo"
copy "LWO\DebrisRockRock0.lwo" "..\Demo Version\LWO\DebrisRockRock0.lwo"
copy "LWO\DebrisRockRock1.lwo" "..\Demo Version\LWO\DebrisRockRock1.lwo"
copy "LWO\DebrisRockSnow0.lwo" "..\Demo Version\LWO\DebrisRockSnow0.lwo"
copy "LWO\DebrisRockSnow1.lwo" "..\Demo Version\LWO\DebrisRockSnow1.lwo"
copy "LWO\Explosion.lwo" "..\Demo Version\LWO\Explosion.lwo"
copy "LWO\ItemAutomaticDefense.lwo" "..\Demo Version\LWO\ItemAutomaticDefense.lwo"
copy "LWO\ItemBatteries.lwo" "..\Demo Version\LWO\ItemBatteries.lwo"
copy "LWO\ItemFuel.lwo" "..\Demo Version\LWO\ItemFuel.lwo"
copy "LWO\ItemHeatSeekWeak.lwo" "..\Demo Version\LWO\ItemHeatSeekWeak.lwo"
copy "LWO\ItemParachutesLOD0.lwo" "..\Demo Version\LWO\ItemParachutesLOD0.lwo"
copy "LWO\ItemParachutesLOD1.lwo" "..\Demo Version\LWO\ItemParachutesLOD1.lwo"
copy "LWO\ItemShieldsLight.lwo" "..\Demo Version\LWO\ItemShieldsLight.lwo"
copy "LWO\ItemShieldsLightPiece0.lwo" "..\Demo Version\LWO\ItemShieldsLightPiece0.lwo"
copy "LWO\ItemShieldsLightPiece1.lwo" "..\Demo Version\LWO\ItemShieldsLightPiece1.lwo"
copy "LWO\ItemShieldsLightPiece2.lwo" "..\Demo Version\LWO\ItemShieldsLightPiece2.lwo"
copy "LWO\Shockwave.lwo" "..\Demo Version\LWO\Shockwave.lwo"
copy "LWO\SkySphere.lwo" "..\Demo Version\LWO\SkySphere.lwo"
copy "LWO\Tank 1943 M18HellCat LOD0.lwo" "..\Demo Version\LWO\Tank 1943 M18HellCat LOD0.lwo"
copy "LWO\Tank 1943 M18HellCat LOD1.lwo" "..\Demo Version\LWO\Tank 1943 M18HellCat LOD1.lwo"
copy "LWO\Tank 1943 M22Locust LOD0.lwo" "..\Demo Version\LWO\Tank 1943 M22Locust LOD0.lwo"
copy "LWO\Tank 1943 M22Locust LOD1.lwo" "..\Demo Version\LWO\Tank 1943 M22Locust LOD1.lwo"
copy "LWO\TankHellCatPiece0.lwo" "..\Demo Version\LWO\TankHellCatPiece0.lwo"
copy "LWO\TankHellCatPiece1.lwo" "..\Demo Version\LWO\TankHellCatPiece1.lwo"
copy "LWO\TankHellCatPiece2.lwo" "..\Demo Version\LWO\TankHellCatPiece2.lwo"
copy "LWO\TankHellCatPiece3.lwo" "..\Demo Version\LWO\TankHellCatPiece3.lwo"
copy "LWO\TankHellCatPiece4.lwo" "..\Demo Version\LWO\TankHellCatPiece4.lwo"
copy "LWO\TankHellCatPiece5.lwo" "..\Demo Version\LWO\TankHellCatPiece5.lwo"
copy "LWO\TankLocustPiece0.lwo" "..\Demo Version\LWO\TankLocustPiece0.lwo"
copy "LWO\TankLocustPiece1.lwo" "..\Demo Version\LWO\TankLocustPiece1.lwo"
copy "LWO\TankLocustPiece2.lwo" "..\Demo Version\LWO\TankLocustPiece2.lwo"
copy "LWO\TankLocustPiece3.lwo" "..\Demo Version\LWO\TankLocustPiece3.lwo"
copy "LWO\TankLocustPiece4.lwo" "..\Demo Version\LWO\TankLocustPiece4.lwo"
copy "LWO\TankLocustPiece5.lwo" "..\Demo Version\LWO\TankLocustPiece5.lwo"
copy "LWO\WeaponAirStrikePlaneLOD0.lwo" "..\Demo Version\LWO\WeaponAirStrikePlaneLOD0.lwo"
copy "LWO\WeaponAirStrikePlaneLOD1.lwo" "..\Demo Version\LWO\WeaponAirStrikePlaneLOD1.lwo"
copy "LWO\WeaponAirStrikeSmallLOD0.lwo" "..\Demo Version\LWO\WeaponAirStrikeSmallLOD0.lwo"
copy "LWO\WeaponAirStrikeSmallLOD1.lwo" "..\Demo Version\LWO\WeaponAirStrikeSmallLOD1.lwo"
copy "LWO\WeaponFunkyBombLOD0.lwo" "..\Demo Version\LWO\WeaponFunkyBombLOD0.lwo"
copy "LWO\WeaponFunkyBombLOD1.lwo" "..\Demo Version\LWO\WeaponFunkyBombLOD1.lwo"
copy "LWO\WeaponMissileLargeLOD0.lwo" "..\Demo Version\LWO\WeaponMissileLargeLOD0.lwo"
copy "LWO\WeaponMissileLargeLOD1.lwo" "..\Demo Version\LWO\WeaponMissileLargeLOD1.lwo"
copy "LWO\WeaponMissileSmallLOD0.lwo" "..\Demo Version\LWO\WeaponMissileSmallLOD0.lwo"
copy "LWO\WeaponMissileSmallLOD1.lwo" "..\Demo Version\LWO\WeaponMissileSmallLOD1.lwo"
copy "LWO\WeaponNapalmSmallLOD0.lwo" "..\Demo Version\LWO\WeaponNapalmSmallLOD0.lwo"
copy "LWO\WeaponNapalmSmallLOD1.lwo" "..\Demo Version\LWO\WeaponNapalmSmallLOD1.lwo"
copy "LWO\WeaponNukeSmallLOD0.lwo" "..\Demo Version\LWO\WeaponNukeSmallLOD0.lwo"
copy "LWO\WeaponNukeSmallLOD1.lwo" "..\Demo Version\LWO\WeaponNukeSmallLOD1.lwo"
copy "LWO\WeaponRailgun.lwo" "..\Demo Version\LWO\WeaponRailgun.lwo"
copy "LWO\WeaponRollerSmallLOD0.lwo" "..\Demo Version\LWO\WeaponRollerSmallLOD0.lwo"
copy "LWO\WeaponRollerSmallLOD1.lwo" "..\Demo Version\LWO\WeaponRollerSmallLOD1.lwo"


md "..\Demo Version\TGA"
copy "TGA\AirStrikeBeacon.tga" "..\Demo Version\TGA\AirStrikeBeacon.tga"
copy "TGA\CentralExplosion.tga" "..\Demo Version\TGA\CentralExplosion.tga"
copy "TGA\DecalBlastHuge.tga" "..\Demo Version\TGA\DecalBlastHuge.tga"
copy "TGA\DecalBlastLarge.tga" "..\Demo Version\TGA\DecalBlastLarge.tga"
copy "TGA\DecalBlastMedium.tga" "..\Demo Version\TGA\DecalBlastMedium.tga"
copy "TGA\DecalBlastSmall.tga" "..\Demo Version\TGA\DecalBlastSmall.tga"
copy "TGA\Explosion.tga" "..\Demo Version\TGA\Explosion.tga"
copy "TGA\Fireball.tga" "..\Demo Version\TGA\Fireball.tga"
copy "TGA\GeneralSpark.tga" "..\Demo Version\TGA\GeneralSpark.tga"
copy "TGA\ItemShieldLight.tga" "..\Demo Version\TGA\ItemShieldLight.tga"
copy "TGA\MissileSmoke.tga" "..\Demo Version\TGA\MissileSmoke.tga"
copy "TGA\Railgun.tga" "..\Demo Version\TGA\Railgun.tga"
copy "TGA\ShockWave.tga" "..\Demo Version\TGA\ShockWave.tga"
copy "TGA\Snowflake.tga" "..\Demo Version\TGA\Snowflake.tga"
md "..\Demo Version\TGA\Stone"
copy /y TGA\Stone\*.tga "..\Demo Version\TGA\Stone"

md "..\Demo Version\BMP"
copy "BMP\BuyFullVersion.bmp" "..\Demo Version\BMP\BuyFullVersion.bmp"
copy "BMP\DebrisRockDirt.bmp" "..\Demo Version\BMP\DebrisRockDirt.bmp"
copy "BMP\DebrisRockGrass.bmp" "..\Demo Version\BMP\DebrisRockGrass.bmp"
copy "BMP\DebrisRockRock.bmp" "..\Demo Version\BMP\DebrisRockRock.bmp"
copy "BMP\DebrisRockSnow.bmp" "..\Demo Version\BMP\DebrisRockSnow.bmp"
copy "BMP\DebrisTexture0.bmp" "..\Demo Version\BMP\DebrisTexture0.bmp"
copy "BMP\DebrisTexture1.bmp" "..\Demo Version\BMP\DebrisTexture1.bmp"
copy "BMP\ItemAutoDefense.bmp" "..\Demo Version\BMP\ItemAutoDefense.bmp"
copy "BMP\ItemBatteries.bmp" "..\Demo Version\BMP\ItemBatteries.bmp"
copy "BMP\ItemFuel.bmp" "..\Demo Version\BMP\ItemFuel.bmp"
copy "BMP\ItemHeatSeekBasic.bmp" "..\Demo Version\BMP\ItemHeatSeekBasic.bmp"
copy "BMP\ItemParachutesLOD0.bmp" "..\Demo Version\BMP\ItemParachutesLOD0.bmp"
copy "BMP\ItemParachutesLOD1.bmp" "..\Demo Version\BMP\ItemParachutesLOD1.bmp"
copy "BMP\Sky2.bmp" "..\Demo Version\BMP\Sky2.bmp"
copy "BMP\Tank 1943HellCat LOD0.bmp" "..\Demo Version\BMP\Tank 1943HellCat LOD0.bmp"
copy "BMP\Tank 1943HellCat LOD1.bmp" "..\Demo Version\BMP\Tank 1943HellCat LOD1.bmp"
copy "BMP\Tank 1943Locust LOD0.bmp" "..\Demo Version\BMP\Tank 1943Locust LOD0.bmp"
copy "BMP\Tank 1943Locust LOD1.bmp" "..\Demo Version\BMP\Tank 1943Locust LOD1.bmp"
copy "BMP\WeaponAirStrikePlaneLOD0.bmp" "..\Demo Version\BMP\WeaponAirStrikePlaneLOD0.bmp"
copy "BMP\WeaponAirStrikePlaneLOD1.bmp" "..\Demo Version\BMP\WeaponAirStrikePlaneLOD1.bmp"
copy "BMP\WeaponAirStrikeSmallLOD0.bmp" "..\Demo Version\BMP\WeaponAirStrikeSmallLOD0.bmp"
copy "BMP\WeaponAirStrikeSmallLOD1.bmp" "..\Demo Version\BMP\WeaponAirStrikeSmallLOD1.bmp"
copy "BMP\WeaponFunkyBombLOD0.bmp" "..\Demo Version\BMP\WeaponFunkyBombLOD0.bmp"
copy "BMP\WeaponFunkyBombLOD1.bmp" "..\Demo Version\BMP\WeaponFunkyBombLOD1.bmp"
copy "BMP\WeaponMissileLargeLOD0.bmp" "..\Demo Version\BMP\WeaponMissileLargeLOD0.bmp"
copy "BMP\WeaponMissileLargeLOD1.bmp" "..\Demo Version\BMP\WeaponMissileLargeLOD1.bmp"
copy "BMP\WeaponMissileSmallLOD0.bmp" "..\Demo Version\BMP\WeaponMissileSmallLOD0.bmp"
copy "BMP\WeaponMissileSmallLOD1.bmp" "..\Demo Version\BMP\WeaponMissileSmallLOD1.bmp"
copy "BMP\WeaponNapalmSmallLOD0.bmp" "..\Demo Version\BMP\WeaponNapalmSmallLOD0.bmp"
copy "BMP\WeaponNapalmSmallLOD1.bmp" "..\Demo Version\BMP\WeaponNapalmSmallLOD1.bmp"
copy "BMP\WeaponNukeSmallLOD0.bmp" "..\Demo Version\BMP\WeaponNukeSmallLOD0.bmp"
copy "BMP\WeaponNukeSmallLOD1.bmp" "..\Demo Version\BMP\WeaponNukeSmallLOD1.bmp"
copy "BMP\WeaponRailgunLOD0.bmp" "..\Demo Version\BMP\WeaponRailgunLOD0.bmp"
copy "BMP\WeaponRollerSmallLOD0.bmp" "..\Demo Version\BMP\WeaponRollerSmallLOD0.bmp"
copy "BMP\WeaponRollerSmallLOD1.bmp" "..\Demo Version\BMP\WeaponRollerSmallLOD1.bmp"
copy "BMP\LoadingGame.bmp" "..\Demo Version\BMP\LoadingGame.bmp"
copy "BMP\LoadingStone.bmp" "..\Demo Version\BMP\LoadingStone.bmp"

md "..\Demo Version\WAV"
copy "WAV\AirPlaneEmit0.wav" "..\Demo Version\WAV\AirPlaneEmit0.wav"
copy "WAV\AirPlaneEngine0.wav" "..\Demo Version\WAV\AirPlaneEngine0.wav"
copy "WAV\AirRaid0.wav" "..\Demo Version\WAV\AirRaid0.wav"
copy "WAV\AmbientNoise0.wav" "..\Demo Version\WAV\AmbientNoise0.wav"
copy "WAV\AmbientNoise1.wav" "..\Demo Version\WAV\AmbientNoise1.wav"
copy "WAV\AmbientNoise2.wav" "..\Demo Version\WAV\AmbientNoise2.wav"
copy "WAV\AmbientNoise3.wav" "..\Demo Version\WAV\AmbientNoise3.wav"
copy "WAV\AmbientNoise4.wav" "..\Demo Version\WAV\AmbientNoise4.wav"
copy "WAV\AmbientNoise5.wav" "..\Demo Version\WAV\AmbientNoise5.wav"
copy "WAV\AmbientNoise6.wav" "..\Demo Version\WAV\AmbientNoise6.wav"
copy "WAV\AmbientNoise7.wav" "..\Demo Version\WAV\AmbientNoise7.wav"
copy "WAV\AmbientNoise8.wav" "..\Demo Version\WAV\AmbientNoise8.wav"
copy "WAV\AmbientNoise9.wav" "..\Demo Version\WAV\AmbientNoise9.wav"
copy "WAV\Applause0.wav" "..\Demo Version\WAV\Applause0.wav"
copy "WAV\BombExplode0.wav" "..\Demo Version\WAV\BombExplode0.wav"
copy "WAV\BombExplode1.wav" "..\Demo Version\WAV\BombExplode1.wav"
copy "WAV\BombExplode2.wav" "..\Demo Version\WAV\BombExplode2.wav"
copy "WAV\Guidance0.wav" "..\Demo Version\WAV\Guidance0.wav"
copy "WAV\HitScanExplode0.wav" "..\Demo Version\WAV\HitScanExplode0.wav"
copy "WAV\ItemActivate0.wav" "..\Demo Version\WAV\ItemActivate0.wav"
copy "WAV\ItemDeactivate0.wav" "..\Demo Version\WAV\ItemDeactivate0.wav"
copy "WAV\MissileExplode0.wav" "..\Demo Version\WAV\MissileExplode0.wav"
copy "WAV\MissileExplode1.wav" "..\Demo Version\WAV\MissileExplode1.wav"
copy "WAV\MissileExplode2.wav" "..\Demo Version\WAV\MissileExplode2.wav"
copy "WAV\Napalm0.wav" "..\Demo Version\WAV\Napalm0.wav"
copy "WAV\ObjectImpact0.wav" "..\Demo Version\WAV\ObjectImpact0.wav"
copy "WAV\ObjectImpact1.wav" "..\Demo Version\WAV\ObjectImpact1.wav"
copy "WAV\Parachute0.wav" "..\Demo Version\WAV\Parachute0.wav"
copy "WAV\ShieldDown0.wav" "..\Demo Version\WAV\ShieldDown0.wav"
copy "WAV\ShieldHit0.wav" "..\Demo Version\WAV\ShieldHit0.wav"
copy "WAV\ShieldHit1.wav" "..\Demo Version\WAV\ShieldHit1.wav"
copy "WAV\ShieldHit2.wav" "..\Demo Version\WAV\ShieldHit2.wav"
copy "WAV\ShieldShatter0.wav" "..\Demo Version\WAV\ShieldShatter0.wav"
copy "WAV\ShieldUp0.wav" "..\Demo Version\WAV\ShieldUp0.wav"
copy "WAV\ShootBomb0.wav" "..\Demo Version\WAV\ShootBomb0.wav"
copy "WAV\ShootHitscan0.wav" "..\Demo Version\WAV\ShootHitscan0.wav"
copy "WAV\ShootMissile0.wav" "..\Demo Version\WAV\ShootMissile0.wav"
copy "WAV\ShotEmit0.wav" "..\Demo Version\WAV\ShotEmit0.wav"
copy "WAV\TankEngine0.wav" "..\Demo Version\WAV\TankEngine0.wav"
copy "WAV\TankEngineStart0.wav" "..\Demo Version\WAV\TankEngineStart0.wav"
copy "WAV\TankExplode0.wav" "..\Demo Version\WAV\TankExplode0.wav"
copy "WAV\TankExplode1.wav" "..\Demo Version\WAV\TankExplode1.wav"
copy "WAV\TankExplode2.wav" "..\Demo Version\WAV\TankExplode2.wav"
copy "WAV\TankHit0.wav" "..\Demo Version\WAV\TankHit0.wav"
copy "WAV\TankHit1.wav" "..\Demo Version\WAV\TankHit1.wav"
copy "WAV\TankImpact0.wav" "..\Demo Version\WAV\TankImpact0.wav"
copy "WAV\TankImpact1.wav" "..\Demo Version\WAV\TankImpact1.wav"

copy Release\*.exe "..\Demo Version"
copy RevisionHistory.txt "..\Demo Version"
pause
