md "..\Full Version"


md "..\Full Version\LWO"
copy "LWO\DebrisGeneral0.lwo" "..\Full Version\LWO\DebrisGeneral0.lwo"
copy "LWO\DebrisGeneral1.lwo" "..\Full Version\LWO\DebrisGeneral1.lwo"
copy "LWO\DebrisGeneral2.lwo" "..\Full Version\LWO\DebrisGeneral2.lwo"
copy "LWO\DebrisGeneral3.lwo" "..\Full Version\LWO\DebrisGeneral3.lwo"
copy "LWO\DebrisGeneral4.lwo" "..\Full Version\LWO\DebrisGeneral4.lwo"
copy "LWO\DebrisRockDirt0.lwo" "..\Full Version\LWO\DebrisRockDirt0.lwo"
copy "LWO\DebrisRockDirt1.lwo" "..\Full Version\LWO\DebrisRockDirt1.lwo"
copy "LWO\DebrisRockGrass0.lwo" "..\Full Version\LWO\DebrisRockGrass0.lwo"
copy "LWO\DebrisRockGrass1.lwo" "..\Full Version\LWO\DebrisRockGrass1.lwo"
copy "LWO\DebrisRockRock0.lwo" "..\Full Version\LWO\DebrisRockRock0.lwo"
copy "LWO\DebrisRockRock1.lwo" "..\Full Version\LWO\DebrisRockRock1.lwo"
copy "LWO\DebrisRockSnow0.lwo" "..\Full Version\LWO\DebrisRockSnow0.lwo"
copy "LWO\DebrisRockSnow1.lwo" "..\Full Version\LWO\DebrisRockSnow1.lwo"
copy "LWO\Explosion.lwo" "..\Full Version\LWO\Explosion.lwo"
copy "LWO\ItemAutomaticDefense.lwo" "..\Full Version\LWO\ItemAutomaticDefense.lwo"
copy "LWO\ItemBatteries.lwo" "..\Full Version\LWO\ItemBatteries.lwo"
copy "LWO\ItemFuel.lwo" "..\Full Version\LWO\ItemFuel.lwo"
copy "LWO\ItemHeatSeekStrong.lwo" "..\Full Version\LWO\ItemHeatSeekStrong.lwo"
copy "LWO\ItemHeatSeekWeak.lwo" "..\Full Version\LWO\ItemHeatSeekWeak.lwo"
copy "LWO\ItemParachutesLOD0.lwo" "..\Full Version\LWO\ItemParachutesLOD0.lwo"
copy "LWO\ItemParachutesLOD1.lwo" "..\Full Version\LWO\ItemParachutesLOD1.lwo"
copy "LWO\ItemShieldsHeavy.lwo" "..\Full Version\LWO\ItemShieldsHeavy.lwo"
copy "LWO\ItemShieldsHeavyPiece0.lwo" "..\Full Version\LWO\ItemShieldsHeavyPiece0.lwo"
copy "LWO\ItemShieldsHeavyPiece1.lwo" "..\Full Version\LWO\ItemShieldsHeavyPiece1.lwo"
copy "LWO\ItemShieldsHeavyPiece2.lwo" "..\Full Version\LWO\ItemShieldsHeavyPiece2.lwo"
copy "LWO\ItemShieldsLight.lwo" "..\Full Version\LWO\ItemShieldsLight.lwo"
copy "LWO\ItemShieldsLightPiece0.lwo" "..\Full Version\LWO\ItemShieldsLightPiece0.lwo"
copy "LWO\ItemShieldsLightPiece1.lwo" "..\Full Version\LWO\ItemShieldsLightPiece1.lwo"
copy "LWO\ItemShieldsLightPiece2.lwo" "..\Full Version\LWO\ItemShieldsLightPiece2.lwo"
copy "LWO\ItemShieldsMedium.lwo" "..\Full Version\LWO\ItemShieldsMedium.lwo"
copy "LWO\ItemShieldsMediumPiece0.lwo" "..\Full Version\LWO\ItemShieldsMediumPiece0.lwo"
copy "LWO\ItemShieldsMediumPiece1.lwo" "..\Full Version\LWO\ItemShieldsMediumPiece1.lwo"
copy "LWO\ItemShieldsMediumPiece2.lwo" "..\Full Version\LWO\ItemShieldsMediumPiece2.lwo"
copy "LWO\Shockwave.lwo" "..\Full Version\LWO\Shockwave.lwo"
copy "LWO\SkySphere.lwo" "..\Full Version\LWO\SkySphere.lwo"
copy "LWO\Tank 1943 M18HellCat LOD0.lwo" "..\Full Version\LWO\Tank 1943 M18HellCat LOD0.lwo"
copy "LWO\Tank 1943 M18HellCat LOD1.lwo" "..\Full Version\LWO\Tank 1943 M18HellCat LOD1.lwo"
copy "LWO\Tank 1943 M22Locust LOD0.lwo" "..\Full Version\LWO\Tank 1943 M22Locust LOD0.lwo"
copy "LWO\Tank 1943 M22Locust LOD1.lwo" "..\Full Version\LWO\Tank 1943 M22Locust LOD1.lwo"
copy "LWO\TankHellCatPiece0.lwo" "..\Full Version\LWO\TankHellCatPiece0.lwo"
copy "LWO\TankHellCatPiece1.lwo" "..\Full Version\LWO\TankHellCatPiece1.lwo"
copy "LWO\TankHellCatPiece2.lwo" "..\Full Version\LWO\TankHellCatPiece2.lwo"
copy "LWO\TankHellCatPiece3.lwo" "..\Full Version\LWO\TankHellCatPiece3.lwo"
copy "LWO\TankHellCatPiece4.lwo" "..\Full Version\LWO\TankHellCatPiece4.lwo"
copy "LWO\TankHellCatPiece5.lwo" "..\Full Version\LWO\TankHellCatPiece5.lwo"
copy "LWO\TankLocustPiece0.lwo" "..\Full Version\LWO\TankLocustPiece0.lwo"
copy "LWO\TankLocustPiece1.lwo" "..\Full Version\LWO\TankLocustPiece1.lwo"
copy "LWO\TankLocustPiece2.lwo" "..\Full Version\LWO\TankLocustPiece2.lwo"
copy "LWO\TankLocustPiece3.lwo" "..\Full Version\LWO\TankLocustPiece3.lwo"
copy "LWO\TankLocustPiece4.lwo" "..\Full Version\LWO\TankLocustPiece4.lwo"
copy "LWO\TankLocustPiece5.lwo" "..\Full Version\LWO\TankLocustPiece5.lwo"
copy "LWO\WeaponAirStrikeLargeLOD0.lwo" "..\Full Version\LWO\WeaponAirStrikeLargeLOD0.lwo"
copy "LWO\WeaponAirStrikeLargeLOD1.lwo" "..\Full Version\LWO\WeaponAirStrikeLargeLOD1.lwo"
copy "LWO\WeaponAirStrikePlaneLOD0.lwo" "..\Full Version\LWO\WeaponAirStrikePlaneLOD0.lwo"
copy "LWO\WeaponAirStrikePlaneLOD1.lwo" "..\Full Version\LWO\WeaponAirStrikePlaneLOD1.lwo"
copy "LWO\WeaponAirStrikeSmallLOD0.lwo" "..\Full Version\LWO\WeaponAirStrikeSmallLOD0.lwo"
copy "LWO\WeaponAirStrikeSmallLOD1.lwo" "..\Full Version\LWO\WeaponAirStrikeSmallLOD1.lwo"
copy "LWO\WeaponFunkyBombLOD0.lwo" "..\Full Version\LWO\WeaponFunkyBombLOD0.lwo"
copy "LWO\WeaponFunkyBombLOD1.lwo" "..\Full Version\LWO\WeaponFunkyBombLOD1.lwo"
copy "LWO\WeaponMissileLargeLOD0.lwo" "..\Full Version\LWO\WeaponMissileLargeLOD0.lwo"
copy "LWO\WeaponMissileLargeLOD1.lwo" "..\Full Version\LWO\WeaponMissileLargeLOD1.lwo"
copy "LWO\WeaponMissileSmallLOD0.lwo" "..\Full Version\LWO\WeaponMissileSmallLOD0.lwo"
copy "LWO\WeaponMissileSmallLOD1.lwo" "..\Full Version\LWO\WeaponMissileSmallLOD1.lwo"
copy "LWO\WeaponNapalmLargeLOD0.lwo" "..\Full Version\LWO\WeaponNapalmLargeLOD0.lwo"
copy "LWO\WeaponNapalmLargeLOD1.lwo" "..\Full Version\LWO\WeaponNapalmLargeLOD1.lwo"
copy "LWO\WeaponNapalmSmallLOD0.lwo" "..\Full Version\LWO\WeaponNapalmSmallLOD0.lwo"
copy "LWO\WeaponNapalmSmallLOD1.lwo" "..\Full Version\LWO\WeaponNapalmSmallLOD1.lwo"
copy "LWO\WeaponNukeLargeLOD0.lwo" "..\Full Version\LWO\WeaponNukeLargeLOD0.lwo"
copy "LWO\WeaponNukeLargeLOD1.lwo" "..\Full Version\LWO\WeaponNukeLargeLOD1.lwo"
copy "LWO\WeaponNukeSmallLOD0.lwo" "..\Full Version\LWO\WeaponNukeSmallLOD0.lwo"
copy "LWO\WeaponNukeSmallLOD1.lwo" "..\Full Version\LWO\WeaponNukeSmallLOD1.lwo"
copy "LWO\WeaponRailgun.lwo" "..\Full Version\LWO\WeaponRailgun.lwo"
copy "LWO\WeaponRollerLargeLOD0.lwo" "..\Full Version\LWO\WeaponRollerLargeLOD0.lwo"
copy "LWO\WeaponRollerLargeLOD1.lwo" "..\Full Version\LWO\WeaponRollerLargeLOD1.lwo"
copy "LWO\WeaponRollerSmallLOD0.lwo" "..\Full Version\LWO\WeaponRollerSmallLOD0.lwo"
copy "LWO\WeaponRollerSmallLOD1.lwo" "..\Full Version\LWO\WeaponRollerSmallLOD1.lwo"


md "..\Full Version\TGA"
copy "TGA\AirStrikeBeacon.tga" "..\Full Version\TGA\AirStrikeBeacon.tga"
copy "TGA\CentralExplosion.tga" "..\Full Version\TGA\CentralExplosion.tga"
copy "TGA\DecalBlastHuge.tga" "..\Full Version\TGA\DecalBlastHuge.tga"
copy "TGA\DecalBlastLarge.tga" "..\Full Version\TGA\DecalBlastLarge.tga"
copy "TGA\DecalBlastMedium.tga" "..\Full Version\TGA\DecalBlastMedium.tga"
copy "TGA\DecalBlastSmall.tga" "..\Full Version\TGA\DecalBlastSmall.tga"
copy "TGA\Explosion.tga" "..\Full Version\TGA\Explosion.tga"
copy "TGA\Fireball.tga" "..\Full Version\TGA\Fireball.tga"
copy "TGA\GeneralSpark.tga" "..\Full Version\TGA\GeneralSpark.tga"
copy "TGA\ItemShieldHeavy.tga" "..\Full Version\TGA\ItemShieldHeavy.tga"
copy "TGA\ItemShieldLight.tga" "..\Full Version\TGA\ItemShieldLight.tga"
copy "TGA\ItemShieldMedium.tga" "..\Full Version\TGA\ItemShieldMedium.tga"
copy "TGA\MissileSmoke.tga" "..\Full Version\TGA\MissileSmoke.tga"
copy "TGA\Railgun.tga" "..\Full Version\TGA\Railgun.tga"
copy "TGA\ShockWave.tga" "..\Full Version\TGA\ShockWave.tga"
copy "TGA\Snowflake.tga" "..\Full Version\TGA\Snowflake.tga"
md "..\Full Version\TGA\Dirt"
copy /y TGA\Dirt\*.tga "..\Full Version\TGA\Dirt"
md "..\Full Version\TGA\Grass"
copy /y TGA\Grass\*.tga "..\Full Version\TGA\Grass"
md "..\Full Version\TGA\Mud"
copy /y TGA\Mud\*.tga "..\Full Version\TGA\Mud"
md "..\Full Version\TGA\Rock"
copy /y TGA\Rock\*.tga "..\Full Version\TGA\Rock"
md "..\Full Version\TGA\Sand"
copy /y TGA\Sand\*.tga "..\Full Version\TGA\Sand"
md "..\Full Version\TGA\Snow"
copy /y TGA\Snow\*.tga "..\Full Version\TGA\Snow"
md "..\Full Version\TGA\Stone"
copy /y TGA\Stone\*.tga "..\Full Version\TGA\Stone"

md "..\Full Version\BMP"
copy "BMP\DebrisRockDirt.bmp" "..\Full Version\BMP\DebrisRockDirt.bmp"
copy "BMP\DebrisRockGrass.bmp" "..\Full Version\BMP\DebrisRockGrass.bmp"
copy "BMP\DebrisRockRock.bmp" "..\Full Version\BMP\DebrisRockRock.bmp"
copy "BMP\DebrisRockSnow.bmp" "..\Full Version\BMP\DebrisRockSnow.bmp"
copy "BMP\DebrisTexture0.bmp" "..\Full Version\BMP\DebrisTexture0.bmp"
copy "BMP\DebrisTexture1.bmp" "..\Full Version\BMP\DebrisTexture1.bmp"
copy "BMP\ItemAutoDefense.bmp" "..\Full Version\BMP\ItemAutoDefense.bmp"
copy "BMP\ItemBatteries.bmp" "..\Full Version\BMP\ItemBatteries.bmp"
copy "BMP\ItemFuel.bmp" "..\Full Version\BMP\ItemFuel.bmp"
copy "BMP\ItemHeatSeekAdvanced.bmp" "..\Full Version\BMP\ItemHeatSeekAdvanced.bmp"
copy "BMP\ItemHeatSeekBasic.bmp" "..\Full Version\BMP\ItemHeatSeekBasic.bmp"
copy "BMP\ItemParachutesLOD0.bmp" "..\Full Version\BMP\ItemParachutesLOD0.bmp"
copy "BMP\ItemParachutesLOD1.bmp" "..\Full Version\BMP\ItemParachutesLOD1.bmp"
copy "BMP\Sky2.bmp" "..\Full Version\BMP\Sky2.bmp"
copy "BMP\Tank 1943HellCat LOD0.bmp" "..\Full Version\BMP\Tank 1943HellCat LOD0.bmp"
copy "BMP\Tank 1943HellCat LOD1.bmp" "..\Full Version\BMP\Tank 1943HellCat LOD1.bmp"
copy "BMP\Tank 1943Locust LOD0.bmp" "..\Full Version\BMP\Tank 1943Locust LOD0.bmp"
copy "BMP\Tank 1943Locust LOD1.bmp" "..\Full Version\BMP\Tank 1943Locust LOD1.bmp"
copy "BMP\WeaponAirStrikeLargeLOD0.bmp" "..\Full Version\BMP\WeaponAirStrikeLargeLOD0.bmp"
copy "BMP\WeaponAirStrikeLargeLOD1.bmp" "..\Full Version\BMP\WeaponAirStrikeLargeLOD1.bmp"
copy "BMP\WeaponAirStrikePlaneLOD0.bmp" "..\Full Version\BMP\WeaponAirStrikePlaneLOD0.bmp"
copy "BMP\WeaponAirStrikePlaneLOD1.bmp" "..\Full Version\BMP\WeaponAirStrikePlaneLOD1.bmp"
copy "BMP\WeaponAirStrikeSmallLOD0.bmp" "..\Full Version\BMP\WeaponAirStrikeSmallLOD0.bmp"
copy "BMP\WeaponAirStrikeSmallLOD1.bmp" "..\Full Version\BMP\WeaponAirStrikeSmallLOD1.bmp"
copy "BMP\WeaponFunkyBombLOD0.bmp" "..\Full Version\BMP\WeaponFunkyBombLOD0.bmp"
copy "BMP\WeaponFunkyBombLOD1.bmp" "..\Full Version\BMP\WeaponFunkyBombLOD1.bmp"
copy "BMP\WeaponMissileLargeLOD0.bmp" "..\Full Version\BMP\WeaponMissileLargeLOD0.bmp"
copy "BMP\WeaponMissileLargeLOD1.bmp" "..\Full Version\BMP\WeaponMissileLargeLOD1.bmp"
copy "BMP\WeaponMissileSmallLOD0.bmp" "..\Full Version\BMP\WeaponMissileSmallLOD0.bmp"
copy "BMP\WeaponMissileSmallLOD1.bmp" "..\Full Version\BMP\WeaponMissileSmallLOD1.bmp"
copy "BMP\WeaponNapalmLargeLOD0.bmp" "..\Full Version\BMP\WeaponNapalmLargeLOD0.bmp"
copy "BMP\WeaponNapalmLargeLOD1.bmp" "..\Full Version\BMP\WeaponNapalmLargeLOD1.bmp"
copy "BMP\WeaponNapalmSmallLOD0.bmp" "..\Full Version\BMP\WeaponNapalmSmallLOD0.bmp"
copy "BMP\WeaponNapalmSmallLOD1.bmp" "..\Full Version\BMP\WeaponNapalmSmallLOD1.bmp"
copy "BMP\WeaponNukeLargeLOD0.bmp" "..\Full Version\BMP\WeaponNukeLargeLOD0.bmp"
copy "BMP\WeaponNukeLargeLOD1.bmp" "..\Full Version\BMP\WeaponNukeLargeLOD1.bmp"
copy "BMP\WeaponNukeSmallLOD0.bmp" "..\Full Version\BMP\WeaponNukeSmallLOD0.bmp"
copy "BMP\WeaponNukeSmallLOD1.bmp" "..\Full Version\BMP\WeaponNukeSmallLOD1.bmp"
copy "BMP\WeaponRailgunLOD0.bmp" "..\Full Version\BMP\WeaponRailgunLOD0.bmp"
copy "BMP\WeaponRollerLargeLOD0.bmp" "..\Full Version\BMP\WeaponRollerLargeLOD0.bmp"
copy "BMP\WeaponRollerLargeLOD1.bmp" "..\Full Version\BMP\WeaponRollerLargeLOD1.bmp"
copy "BMP\WeaponRollerSmallLOD0.bmp" "..\Full Version\BMP\WeaponRollerSmallLOD0.bmp"
copy "BMP\WeaponRollerSmallLOD1.bmp" "..\Full Version\BMP\WeaponRollerSmallLOD1.bmp"
copy "BMP\LoadingDirt.bmp" "..\Full Version\BMP\LoadingDirt.bmp"
copy "BMP\LoadingGrass.bmp" "..\Full Version\BMP\LoadingGrass.bmp"
copy "BMP\LoadingMud.bmp" "..\Full Version\BMP\LoadingMud.bmp"
copy "BMP\LoadingRock.bmp" "..\Full Version\BMP\LoadingRock.bmp"
copy "BMP\LoadingSand.bmp" "..\Full Version\BMP\LoadingSand.bmp"
copy "BMP\LoadingSnow.bmp" "..\Full Version\BMP\LoadingSnow.bmp"
copy "BMP\LoadingGame.bmp" "..\Full Version\BMP\LoadingGame.bmp"
copy "BMP\LoadingStone.bmp" "..\Full Version\BMP\LoadingStone.bmp"

md "..\Full Version\WAV"
copy "WAV\AirPlaneEmit0.wav" "..\Full Version\WAV\AirPlaneEmit0.wav"
copy "WAV\AirPlaneEngine0.wav" "..\Full Version\WAV\AirPlaneEngine0.wav"
copy "WAV\AirRaid0.wav" "..\Full Version\WAV\AirRaid0.wav"
copy "WAV\AmbientNoise0.wav" "..\Full Version\WAV\AmbientNoise0.wav"
copy "WAV\AmbientNoise1.wav" "..\Full Version\WAV\AmbientNoise1.wav"
copy "WAV\AmbientNoise2.wav" "..\Full Version\WAV\AmbientNoise2.wav"
copy "WAV\AmbientNoise3.wav" "..\Full Version\WAV\AmbientNoise3.wav"
copy "WAV\AmbientNoise4.wav" "..\Full Version\WAV\AmbientNoise4.wav"
copy "WAV\AmbientNoise5.wav" "..\Full Version\WAV\AmbientNoise5.wav"
copy "WAV\AmbientNoise6.wav" "..\Full Version\WAV\AmbientNoise6.wav"
copy "WAV\AmbientNoise7.wav" "..\Full Version\WAV\AmbientNoise7.wav"
copy "WAV\AmbientNoise8.wav" "..\Full Version\WAV\AmbientNoise8.wav"
copy "WAV\AmbientNoise9.wav" "..\Full Version\WAV\AmbientNoise9.wav"
copy "WAV\Applause0.wav" "..\Full Version\WAV\Applause0.wav"
copy "WAV\BombExplode0.wav" "..\Full Version\WAV\BombExplode0.wav"
copy "WAV\BombExplode1.wav" "..\Full Version\WAV\BombExplode1.wav"
copy "WAV\BombExplode2.wav" "..\Full Version\WAV\BombExplode2.wav"
copy "WAV\Guidance0.wav" "..\Full Version\WAV\Guidance0.wav"
copy "WAV\HitScanExplode0.wav" "..\Full Version\WAV\HitScanExplode0.wav"
copy "WAV\ItemActivate0.wav" "..\Full Version\WAV\ItemActivate0.wav"
copy "WAV\ItemDeactivate0.wav" "..\Full Version\WAV\ItemDeactivate0.wav"
copy "WAV\MissileExplode0.wav" "..\Full Version\WAV\MissileExplode0.wav"
copy "WAV\MissileExplode1.wav" "..\Full Version\WAV\MissileExplode1.wav"
copy "WAV\MissileExplode2.wav" "..\Full Version\WAV\MissileExplode2.wav"
copy "WAV\Napalm0.wav" "..\Full Version\WAV\Napalm0.wav"
copy "WAV\ObjectImpact0.wav" "..\Full Version\WAV\ObjectImpact0.wav"
copy "WAV\ObjectImpact1.wav" "..\Full Version\WAV\ObjectImpact1.wav"
copy "WAV\Parachute0.wav" "..\Full Version\WAV\Parachute0.wav"
copy "WAV\ShieldDown0.wav" "..\Full Version\WAV\ShieldDown0.wav"
copy "WAV\ShieldHit0.wav" "..\Full Version\WAV\ShieldHit0.wav"
copy "WAV\ShieldHit1.wav" "..\Full Version\WAV\ShieldHit1.wav"
copy "WAV\ShieldHit2.wav" "..\Full Version\WAV\ShieldHit2.wav"
copy "WAV\ShieldShatter0.wav" "..\Full Version\WAV\ShieldShatter0.wav"
copy "WAV\ShieldUp0.wav" "..\Full Version\WAV\ShieldUp0.wav"
copy "WAV\ShootBomb0.wav" "..\Full Version\WAV\ShootBomb0.wav"
copy "WAV\ShootHitscan0.wav" "..\Full Version\WAV\ShootHitscan0.wav"
copy "WAV\ShootMissile0.wav" "..\Full Version\WAV\ShootMissile0.wav"
copy "WAV\ShotEmit0.wav" "..\Full Version\WAV\ShotEmit0.wav"
copy "WAV\TankEngine0.wav" "..\Full Version\WAV\TankEngine0.wav"
copy "WAV\TankEngineStart0.wav" "..\Full Version\WAV\TankEngineStart0.wav"
copy "WAV\TankExplode0.wav" "..\Full Version\WAV\TankExplode0.wav"
copy "WAV\TankExplode1.wav" "..\Full Version\WAV\TankExplode1.wav"
copy "WAV\TankExplode2.wav" "..\Full Version\WAV\TankExplode2.wav"
copy "WAV\TankHit0.wav" "..\Full Version\WAV\TankHit0.wav"
copy "WAV\TankHit1.wav" "..\Full Version\WAV\TankHit1.wav"
copy "WAV\TankImpact0.wav" "..\Full Version\WAV\TankImpact0.wav"
copy "WAV\TankImpact1.wav" "..\Full Version\WAV\TankImpact1.wav"

copy Release\*.exe "..\Full Version"
copy RevisionHistory.txt "..\Demo Version"
pause
